#!rake
# vim:set fileencoding=utf-8 ts=2 sw=2 sts=2 et:

require_relative 'lib/image_register'
require 'pp'
require 'pathname'


CSV_LIST = FileList.new("#{__dir__}/watched/*.csv")
TIME_STAMP_LIST = CSV_LIST.gsub('/watched/', '/watched/timestamp/').ext('.ts')
TIME_STAMP_DIR = "#{__dir__}/watched/timestamp"

require 'rake/clean'
CLEAN.include(TIME_STAMP_DIR)
CLOBBER.include(Db::DB_FILE)

directory TIME_STAMP_DIR
task :default => [:import_md5]

desc 'import md5'
task :import_md5 => [TIME_STAMP_DIR, *TIME_STAMP_LIST]

PROC_FIND_CSV = proc{|task_name|
  dest = Pathname(task_name)
  src = dest.parent.parent.join(dest.basename).sub_ext('.csv')
  next src.to_s
}

rule '.ts' => [PROC_FIND_CSV] do |t|
  puts "import md5 from '#{t.source}'"
  ImageRegister::regist(t.source)
  sh "touch #{t.name.gsub("'", "\\\\'")}"
end
